name: 🧪 MySQL Connection Test

on:
  workflow_dispatch:
    inputs:
      verbose:
        description: 'Verbose output'
        required: false
        default: false
        type: boolean

jobs:
  mysql-test:
    name: 🔍 Test połączenia MySQL
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    env:
      PYTHONUNBUFFERED: 1
      
    steps:
      - name: 📥 Checkout kodu
        uses: actions/checkout@v4
        
      - name: 🐍 Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: 🔧 Zainstaluj system dependencies dla MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y default-libmysqlclient-dev build-essential pkg-config
          
      - name: 📦 Zainstaluj MySQL connectors
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install mysql-connector-python==8.2.0 PyMySQL==1.1.0 python-dotenv
          
      - name: 🔍 Test importów
        run: |
          python -c "
          import sys
          print(f'🐍 Python version: {sys.version}')
          print('📦 Sprawdzanie dostępnych connectorów...')
          
          try:
              import mysql.connector
              print('✅ mysql.connector: AVAILABLE')
              print(f'   Version: {mysql.connector.__version__}')
          except ImportError as e:
              print(f'❌ mysql.connector: FAILED - {e}')
          
          try:
              import pymysql
              print('✅ PyMySQL: AVAILABLE')
              print(f'   Version: {pymysql.__version__}')
          except ImportError as e:
              print(f'❌ PyMySQL: FAILED - {e}')
          
          print('📦 Zainstalowane pakiety MySQL:')
          import pkg_resources
          installed = [d.project_name for d in pkg_resources.working_set]
          mysql_packages = [p for p in installed if 'mysql' in p.lower() or 'pymysql' in p.lower()]
          for pkg in mysql_packages:
              print(f'   - {pkg}')
          "
          
      - name: 🧪 Test połączenia z bazą danych
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        run: |
          python -c "
          import os
          
          print('🔍 Test połączenia z bazą MySQL...')
          
          # Sprawdź zmienne środowiskowe
          required_vars = ['MYSQL_HOST', 'MYSQL_PORT', 'MYSQL_USER', 'MYSQL_PASSWORD', 'MYSQL_DATABASE']
          missing_vars = [var for var in required_vars if not os.getenv(var)]
          
          if missing_vars:
              print(f'❌ Brakujące zmienne środowiskowe: {missing_vars}')
              exit(1)
          
          print(f'🏢 Host: {os.environ.get(\"MYSQL_HOST\", \"not_set\")}')
          print(f'🔌 Port: {os.environ.get(\"MYSQL_PORT\", \"not_set\")}')
          print(f'👤 User: {os.environ.get(\"MYSQL_USER\", \"not_set\")}')
          print(f'🗄️ Database: {os.environ.get(\"MYSQL_DATABASE\", \"not_set\")}')
          
          # Test połączenia z fallback
          connection_successful = False
          
          # Próba 1: mysql.connector
          try:
              import mysql.connector
              print('📦 Testowanie mysql.connector...')
              
              conn = mysql.connector.connect(
                  host=os.environ['MYSQL_HOST'],
                  port=int(os.environ['MYSQL_PORT']),
                  user=os.environ['MYSQL_USER'],
                  password=os.environ['MYSQL_PASSWORD'],
                  database=os.environ['MYSQL_DATABASE']
              )
              print('✅ mysql.connector: CONNECTION OK')
              
              cursor = conn.cursor()
              cursor.execute('SELECT VERSION()')
              version = cursor.fetchone()[0]
              print(f'📊 MySQL version: {version}')
              
              cursor.execute(\"SHOW TABLES LIKE 'nieruchomosci'\")
              table_exists = cursor.fetchone() is not None
              print(f'🗄️ Tabela nieruchomosci: {\"EXISTS\" if table_exists else \"NOT FOUND\"}')
              
              if table_exists:
                  cursor.execute('SELECT COUNT(*) FROM nieruchomosci')
                  count = cursor.fetchone()[0]
                  print(f'📊 Liczba rekordów: {count:,}')
              
              conn.close()
              connection_successful = True
              
          except ImportError as e:
              print(f'❌ mysql.connector import failed: {e}')
          except Exception as e:
              print(f'❌ mysql.connector connection failed: {e}')
          
          # Próba 2: PyMySQL (jeśli pierwsza nie powiodła się)
          if not connection_successful:
              try:
                  import pymysql
                  print('📦 Testowanie PyMySQL...')
                  
                  conn = pymysql.connect(
                      host=os.environ['MYSQL_HOST'],
                      port=int(os.environ['MYSQL_PORT']),
                      user=os.environ['MYSQL_USER'],
                      password=os.environ['MYSQL_PASSWORD'],
                      database=os.environ['MYSQL_DATABASE']
                  )
                  print('✅ PyMySQL: CONNECTION OK')
                  
                  cursor = conn.cursor()
                  cursor.execute('SELECT VERSION()')
                  version = cursor.fetchone()[0]
                  print(f'📊 MySQL version: {version}')
                  
                  cursor.execute(\"SHOW TABLES LIKE 'nieruchomosci'\")
                  table_exists = cursor.fetchone() is not None
                  print(f'🗄️ Tabela nieruchomosci: {\"EXISTS\" if table_exists else \"NOT FOUND\"}')
                  
                  if table_exists:
                      cursor.execute('SELECT COUNT(*) FROM nieruchomosci')
                      count = cursor.fetchone()[0]
                      print(f'📊 Liczba rekordów: {count:,}')
                  
                  conn.close()
                  connection_successful = True
                  
              except ImportError as e:
                  print(f'❌ PyMySQL import failed: {e}')
              except Exception as e:
                  print(f'❌ PyMySQL connection failed: {e}')
          
          if connection_successful:
              print('🎉 Test połączenia zakończony SUKCESEM!')
          else:
              print('💥 Test połączenia NIEUDANY!')
              exit(1)
          " 